# Generated by Django 4.2.6 on 2023-10-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_target_muscle', models.CharField(max_length=255)),
                ('secondary_target_muscle', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
