# Generated by Django 4.2.6 on 2023-10-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_exerciseset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseSet',
        ),
        migrations.AddField(
            model_name='exercise',
            name='number_of_sets',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='exercise',
            name='rep_range',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
