# Generated by Django 4.2.6 on 2023-10-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_delete_exerciseset_exercise_number_of_sets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('day_number', models.IntegerField()),
                ('description', models.TextField()),
                ('exercises', models.ManyToManyField(blank=True, null=True, to='plan.exercise')),
            ],
        ),
    ]
