# Generated by Django 4.2.6 on 2023-10-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_subplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplan',
            name='exercises',
            field=models.ManyToManyField(to='plan.exercise'),
        ),
    ]
