# Generated by Django 4.2.6 on 2023-10-22 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_subplan_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_plans', to='plan.plan'),
        ),
    ]
