# Generated by Django 4.2.6 on 2023-10-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity_in_grams', models.IntegerField()),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calories', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='diet',
            name='sub_diets',
        ),
    ]
