# Generated by Django 4.2.6 on 2023-10-26 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_food_remove_diet_sub_diets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('week_number', models.IntegerField()),
                ('day_number', models.IntegerField()),
                ('description', models.TextField()),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine', to='diet.diet')),
            ],
        ),
        migrations.DeleteModel(
            name='SubDiet',
        ),
    ]
