# Generated by Django 4.2.6 on 2023-10-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_routine_delete_subdiet'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='breakfast',
            field=models.ManyToManyField(related_name='breakfast', to='diet.food'),
        ),
        migrations.AddField(
            model_name='routine',
            name='dinner',
            field=models.ManyToManyField(related_name='dinner', to='diet.food'),
        ),
        migrations.AddField(
            model_name='routine',
            name='lunch',
            field=models.ManyToManyField(related_name='lunch', to='diet.food'),
        ),
        migrations.AddField(
            model_name='routine',
            name='snack_1',
            field=models.ManyToManyField(related_name='snack_1', to='diet.food'),
        ),
        migrations.AddField(
            model_name='routine',
            name='snack_2',
            field=models.ManyToManyField(related_name='snack_2', to='diet.food'),
        ),
        migrations.AddField(
            model_name='routine',
            name='snack_3',
            field=models.ManyToManyField(related_name='snack_3', to='diet.food'),
        ),
    ]
