# Generated by Django 4.2.6 on 2023-10-26 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plan.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet', '0004_routine_breakfast_routine_dinner_routine_lunch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='created_foods', to=settings.AUTH_USER_MODEL, validators=[plan.validators.custom_coach_validator]),
            preserve_default=False,
        ),
    ]
