# Generated by Django 4.2.6 on 2023-11-09 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet', '0007_alter_diet_options_alter_routine_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_plans', to=settings.AUTH_USER_MODEL, verbose_name='شاگرد'),
        ),
    ]
