# Generated by Django 4.2.6 on 2023-11-09 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gym',
            options={'verbose_name': 'سالن ورزش', 'verbose_name_plural': 'سالن ورزش'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'دیدگاه', 'verbose_name_plural': 'دیدگاه ها'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'رسانه اجتماعی', 'verbose_name_plural': 'رسنه های اجتماعی'},
        ),
        migrations.AddField(
            model_name='gym',
            name='monthly_tuition_toman',
            field=models.IntegerField(default=250000, verbose_name='شهریه ماهانه (تومان)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gym',
            name='address',
            field=models.CharField(max_length=255, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='days_closed',
            field=models.CharField(max_length=255, verbose_name='روزهای تعطیل'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='hour_close',
            field=models.TimeField(verbose_name='ساعت بستن'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='hour_open',
            field=models.TimeField(verbose_name='ساعت شروع'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='number',
            field=models.CharField(max_length=255, unique=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مالک'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='review',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='gym.gym', verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='social',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='gym.gym', verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.CharField(max_length=255, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
    ]
