# Generated by Django 4.2.6 on 2023-11-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_gym_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='monthly_tuition_toman',
            field=models.IntegerField(blank=True, null=True, verbose_name='شهریه ماهانه (تومان)'),
        ),
    ]
