# Generated by Django 4.2.6 on 2023-10-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_num_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
